name: Magento Caller
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Cypress config file (choose predefined or enter manually)"
        type: choice
        required: false
        default: "login"
        options:
          - login
          - smoke
          - cart
          - custom
          - checkout
      customTag:
        description: "Custom Cypress config file (used if 'custom' is selected)"
        type: string
        required: false
      browser:
        description: "Browser to run the test"
        type: choice
        required: false
        default: "chrome"
        options:
            - electron
            - chrome
            - edge
jobs:
  invoke-default-workflow:
    uses: lssoliveira/magento-web-test/.github/workflows/magento-deafult.yml@main
    with:
      tag: ${{ inputs.tag }}
      browser: ${{ inputs.browser }}
      customTag: ${{ inputs.customTag }}
