name: Magento Default
on:
  workflow_call:
    inputs:
      tag:
        description: "Tag of the test"
        type: string
        required: true
        default: login
      browser:
        description: "Browser of the test"
        type: string
        required: true
        default: chrome
      customTag: 
        description: "Set the custom Tag if exist"
        type: string
        required: false

jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install Cypress dependencies
        run: |
          npm ci
          npm install -g allure-commandline
          npx cypress install

      - name: Run Cypress tests
        env:
          CYPRESS_PASS_DEFAULT: ${{ secrets.CYPRESS_PASS_DEFAULT }}
        run: |
          if [[ -n "${{ inputs.customTag }}" ]]; then
            npm run cypress:run:${{ inputs.customTag }} -- --browser=${{ github.event.inputs.browser }}
          else
            npm run cypress:run:${{ github.event.inputs.tag }} -- --browser=${{ github.event.inputs.browser }}
          fi

      - name: Generate Allure report
        if: always()
        run: |
          npm run allure:generete

      - name: Output Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 10
