name: Magento Parameterized Test
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Select the tag"
        required: true
        default: "e2e"
        type: choice
        options:
          - full
          - e2e
          - smoke
          - login
          - register
          - account
          - browse
          - cart
          - checkout
      browser:
        description: "Selecione the browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - chrome
          - electron
          - edge

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install Cypress dependencies
        run: |
          npm ci
          npm install -g allure-commandline
          npx cypress install

      - name: Run Cypress tests
        env:
          CYPRESS_PASS_DEFAULT: ${{ secrets.CYPRESS_PASS_DEFAULT }}
        run: |
          npm run cypress:run:${{ github.event.inputs.tag }} -- --browser=${{ github.event.inputs.browser }}

      - name: Generate Allure report
        if: always()
        run: |
          npm run allure:generete

      - name: Output Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 10
